---
title: "MSDS 7349-HW3"
author: "Daniel Byrne"
date: "April 8, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Exercise 1: UNIX Password Cracker (30)

1. Write the cracker.py program. Turn in the code and output. 


```{python}

```

2. Identify from where you can retrieve the salt value used in generating the signature



# Exercise 2: Zip File Password Cracker (30)


1-	Write a script to test the use of the zipfile library (10)

2-	Use the except Exception handler to catch exceptions and print them out when an incorrect password is used. (10)

3-	Write a script that performs a dictionary attack on the password protected zip file. Execute your script and turn in the code and output. (10)



# Exercise 3: Port Scanner (40)

1-Create a script that iterates through a range of IP addresses and, for each IP address, will identify the active ports available for that IP address (20)

2- Download and install the nmap port scanning software from nmap.org. Utilize nmap to identify the operating system and the open ports of devices on a range of IP addresses (20)

